// Bundle the browser game's rules engine into an ES module for the Worker.
// The browser loads these files as plain scripts sharing globals; here they
// are concatenated into one module scope and the parts the server needs are
// exported. Nothing in these files touches the DOM.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const src = new URL('../../nuxt-site/public/game/', import.meta.url);
const files = ['constants.js', 'geometry.js', 'state.js', 'rules.js', 'brain.js'];
let out = '// Generated by game-server/scripts/build-engine.mjs from nuxt-site/public/game. Do not edit.\n/* eslint-disable */\n';
for (const f of files) out += `\n// ────── ${f} ──────\n` + readFileSync(new URL(f, src), 'utf8') + '\n';
out += `
export const engine = {
  get G() { return G; },
  set G(v) { G = v; },
  setRand, seededRandom, setAiEffort,
  newGame, act, aiNextAction, scoreBreakdown, inGame, seatName, islands, touchingIslands, turnIsOver, eventsDuration, shipSlots, slotWorld, traceShot, wobbleShot, aimedShot, shotPath, pathAt, fittingWorld, applyHit, hasTurret, nextToRestore, fittingLayout, oneFitting, islandSlots, islandGunOrigin,
  FACTION_DEFS, FACTION_ORDER, PALETTE, factionId, MAX_SEATS, RULES_VERSION,
};
`;
const target = fileURLToPath(new URL('../src/engine.gen.js', import.meta.url));
writeFileSync(target, out);
console.log('engine bundled:', target);
